### ISSUE TITLE
how to build quadtree?

### ISSUE THREAD

**Issue by sundylink** [timohausmann/quadtree-js#10]
In large data point segments, how do you operate some queries, etc. How do you construct quadtrees with rectangles or line segments?

@timohausmann

**Comment by timohausmann** [comment]
This implementation can only query for rectangles (`retrieve` function). 

Check out https://github.com/CorentinTh/quadtree-js to query for circles or custom queries like line segments (`query` function).

**Comment by timohausmann** [comment]
Continuing this request here: 

_Adding support for more primitives checks #16_
