### ISSUE TITLE
Rounding sub quad bounds

### ISSUE THREAD

**Issue by gpbmike** [timohausmann/quadtree-js#11]
While using your quadtree implementation with geographic data I noticed in the `split` method the bounds are being rounded.

https://github.com/timohausmann/quadtree-js/blob/1cabf504825ace9952933029404bd58899be1db2/quadtree.js#L60-L63

In my case it rounds latitude and longitude. 

For example:

https://www.google.com/maps/@37.8113896,-119.7013997,9.98z

rounds to

https://www.google.com/maps/@37,-119,9.98z

I could transform all of my coordinates to some intermediate values but before I do that I wanted to just check in with you. Thanks.

**Comment by timohausmann** [comment]
Good point, I removed the rounding function to allow float boundaries.
