### ISSUE TITLE
update elements?

### ISSUE THREAD

**Issue by Llorx** [timohausmann/quadtree-js#12]
As pointed out in the README, well, I think that updating points is a great feature to maintain.

The usual thing for this is the typical collision detector for games.

**Comment by prescientmoon** [comment]
I too would like to see this implemented

**Comment by timohausmann** [comment]
This is now available in [quadtree-_TS_](https://github.com/timohausmann/quadtree-ts) 
Example: https://timohausmann.github.io/quadtree-ts/examples/update/

**Comment by lxt610** [comment]
您好，你的邮件已经收到！我会尽快回复你！谢谢！
    


    ----------------------------------------------------------------
QQ:11665374

    ***@***.***
