### ISSUE TITLE
TypeError: t is Undefined

### ISSUE THREAD

**Issue by Druidpeter** [timohausmann/quadtree-js#15]
I include the javascript library like so, as described in the tutorial.

` <script src="/static/quadtree.min.js"></script>`

And the code which attempts to use the quadtree:

```
        // Clear the quadtree of all entities.
        this.quadTree.clear();

        // Re-insert soldiers into quadtree.
        for(i = 0; i < this.troops.length; i++){
            var object = {
                x: this.troops[i].x,
                y: this.troops[i].y,
                width: this.troops[i].width,
                height: this.troops[i].height
            }
            
            // this.quadTree.insert(this.troops[i]);
            this.quadTree.insert(this.object);
        }
```

And the code which creates the quadtree:

```
    this.quadTree = new Quadtree({
        x: 0, y: 0, width: 1800, height: 1350
    }, 5);
```

When attempting to load the page in Firefox, I receive a TypeError exception: 't' is undefined. What on earth is going on?

**Comment by timohausmann** [comment]
Hey,
`this.quadTree.insert(this.object)` is this valid or should it be `this.quadTree.insert(object)` (without `this`)?

If the problem persists:
Please try the unminified version so we know what this undefined `t` is exactly. 
Do you use Typescript?

**Comment by Druidpeter** [comment]
Ah, sorry. The `var object` was just my testing code. The original code is this:

```
        for(i = 0; i < this.troops.length; i++){
            this.quadTree.insert(this.troops[i]);
        }
```

`this.troops` is an array containing objects which have x, y, width, and height attributes, along with other attributes as well. At first I thought that the object only needed to contain the required attributes as opposed to explicitly extending from an object class that ONLY had x, y, width, and height attributes?

When running the call through the unminified version of your code, it looks like `pRect` has a value of undefined immediately inside the `this.quadTree.insert(this.troops[i])` method call. So I can only assume that somehow `this.troops[i]` doesn't meet the requirements for being passed to the call?

**Comment by Druidpeter** [comment]
I figured it out. The this.troops[i] array was being built from multiple sources, and some of these sources were overriding others, leaving sections of undefined cells in the array. All is good now. Sorry for the trouble. ^^;

**Comment by timohausmann** [comment]
No worries and good luck with your project!
