### ISSUE TITLE
Adding a licence file

### ISSUE THREAD

**Issue by egel** [timohausmann/quadtree-js#19]
Hello Timo,

First of all great work with the library.

I am writing to you as I noticed that your awesome library is missing a proper LICENCE file. I would be great if we could add it here.
If you're out of time atm, can also prepare a PR for you 🙂 

Best, 
Maciej

**Comment by timohausmann** [comment]
Hey, thanks for your input, a LICENSE.md is a good idea, I only had this [note in the .js file](https://github.com/timohausmann/quadtree-js/blob/master/quadtree.js#L4).

Fixed in https://github.com/timohausmann/quadtree-js/commit/1e2efc48489a2626d58cb79a5e6740108e6cd589
