### ISSUE TITLE
is the width and height from the center or from a corner?

### ISSUE THREAD

**Issue by MixaMega** [timohausmann/quadtree-js#20]
![image](https://github.com/timohausmann/quadtree-js/assets/93724648/85bfa070-0ef1-49e5-ad16-0d06e0c02005)
the x and y are 0, the width and height are 10, would it be like A or like B

**Comment by timohausmann** [comment]
By default it's like B, so no negative space is used.
If your objects are like A you can easily convert them during insert/retrieve.
Feel free to ask if you need more help, please close the issue if it's solved.

**Comment by MixaMega** [comment]
thanks, got a bit confused by the example, it says that the x and y are mouse's and that the height and width are 20 but the mouse is in the middle of the square

**Comment by timohausmann** [comment]
Ah okay, true, if you look into the script you see that the "cursor" is offset to the top and left by half the size to center it at the mouse position.
https://github.com/timohausmann/quadtree-js/blob/master/docs/simple.html#L184
