### ISSUE TITLE
Modify and remove objects from quad-tree

### ISSUE THREAD

**Issue by martindrapeau** [timohausmann/quadtree-js#3]
In your fiddle you clear the quad-tree at every animation frame.
I need a more granular approach - to be able to:
1) Modify the coordinates of an object (x, y, width and height)
2) Remove an object
I'm hoping to use your quad-tree inside of [Backbone Game Engine](http://martindrapeau.github.io/backbone-game-engine/).

**Comment by timohausmann** [comment]
Hi,
I created a [branch](https://github.com/timohausmann/quadtree-js/tree/hitman) that allows you to remove and change single objects.

It uses some new functions, mainly Quadtree.removeObject() and Quadtree.cleanup(). More infos can be found at the [demo](http://timohausmann.de/quadtree.js/hitman/).

How do you manage your quadtree objects? Do you insert your game objects directly, or do you have some kind of helper objects for the coordinates? In the latter case this branch might not be the best solution.

Feel free to ask or tell me more about your intended usage ;-)

**Comment by martindrapeau** [comment]
I do add the object - so your implementation is exactly what's required. On a side-note, your quad-tree is working flawlessly in the game I'm writing. I also added it to [Backbone Game Engine](http://martindrapeau.github.io/backbone-game-engine/). Thanks so much.

**Comment by timohausmann** [comment]
Thanks, I'm glad to hear that! Have fun!
