### ISSUE TITLE
hello,i'm chinese,My English is very terrible.I want to how to use this quadtreejs in nodejs

### ISSUE THREAD

**Issue by whaqzhzd** [timohausmann/quadtree-js#5]

**Comment by whaqzhzd** [comment]
if (('undefined' !== typeof module) && module.exports) {
        module.exports = Quadtree;
    }else{
        _window.Quadtree = Quadtree;
    }

**Comment by timohausmann** [comment]
Hi, I don't know node.js very well, sorry.

**Comment by timohausmann** [comment]
This repository now has support for npm and module.exports.
