### ISSUE TITLE
This visualization looks good, but there are too many objects on parent node

### ISSUE THREAD

**Issue by crazyyi** [timohausmann/quadtree-js#8]
Sometimes I still need to compare half size of the entire object list. This way the algorithm is not very efficient as it is supposed to be. But this is a good demonstration. Maybe there is a better way yet to be found out.

**Comment by timohausmann** [comment]
Hi Aaron, have you tried setting higher values for max_objects and max_levels?
Maybe you wanna check out Spatial Hashing, which follows another approach:
http://zufallsgenerator.github.io/2014/01/26/visually-comparing-algorithms/
https://www.gamedev.net/resources/_/technical/game-programming/spatial-hashing-r2697

**Comment by crazyyi** [comment]
@timohausmann Thanks I have actually tried that approach and tweaked your html file visualization. The Spatial Hashing does a good job in collision detection among similar size objects. The number of candidate objects is significantly lower than using the quadtree method.

**Comment by timohausmann** [comment]
I took another look at this issue and it has been resolved with the new version 1.2.0

#6
