### ISSUE TITLE
Quad Tree should only store objects on leaf nodes

### ISSUE THREAD

**Issue by saliksyed** [timohausmann/quadtree-js#9]
Hey there -- thank you for the nice QuadTree implementation! However I'm noticing that there are often objects stored on the parent nodes as well as child nodes -- this shouldn't be the case. 

See: http://stackoverflow.com/questions/4981866/quadtree-for-2d-collision-detection

**Comment by timohausmann** [comment]
Hi, I cannot replicate the Quadtree storing objects at two nodes at once, can you post an example code of that happening?

The steps described in the stackoverflow answer are different from this implentation; here you can't delete single objects and you cannot check for collision.

**Comment by timohausmann** [comment]
I took another look at this issue and it has been resolved with the new version 1.2.0

#6
